-- Auto-generated by scripts/migrate-json-to-sql.js

-- Generated at: 2026-03-16T15:17:35.552Z

BEGIN;


INSERT INTO roles (name, description) VALUES
  ('user','default user'),
  ('vip','vip user'),
  ('admin','admin user'),
  ('moderator','moderator user')
ON CONFLICT (name) DO NOTHING;





-- user_profiles via username join
INSERT INTO user_profiles (user_id, display_name, bio, gender, age, city, occupation, relationship_goal_id, online_status)
SELECT u.id, v.display_name, v.bio, v.gender, v.age, v.city, v.occupation, NULL, v.online_status
FROM (
  VALUES
  
) AS v(username, display_name, bio, gender, age, city, occupation, relationship_goal, online_status)
JOIN users u ON u.username = v.username;



INSERT INTO user_wallets (user_id, balance)
SELECT u.id, v.balance
FROM (
  VALUES
  
) AS v(username, balance)
JOIN users u ON u.username = v.username
ON CONFLICT (user_id) DO UPDATE SET balance = EXCLUDED.balance;


COMMIT;
